// Code generated by "stringer -type JetVersion"; DO NOT EDIT

package version

import "fmt"

const _JetVersion_name = "Jet3Jet4"

var _JetVersion_index = [...]uint8{0, 4, 8}

func (i JetVersion) String() string {
	if i >= JetVersion(len(_JetVersion_index)-1) {
		return fmt.Sprintf("JetVersion(%d)", i)
	}
	return _JetVersion_name[_JetVersion_index[i]:_JetVersion_index[i+1]]
}
